--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Postgres.app)
-- Dumped by pg_dump version 16.2 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: address_type; Type: TYPE; Schema: public; Owner: figgefenk
--

CREATE TYPE public.address_type AS ENUM (
    'billing',
    'shipping',
    'mailing'
);


ALTER TYPE public.address_type OWNER TO figgefenk;

--
-- Name: order_status; Type: TYPE; Schema: public; Owner: figgefenk
--

CREATE TYPE public.order_status AS ENUM (
    'checkout',
    'pending',
    'paid',
    'preparing',
    'shipped',
    'fulfilled'
);


ALTER TYPE public.order_status OWNER TO figgefenk;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.addresses (
    id integer NOT NULL,
    user_id integer,
    type public.address_type NOT NULL,
    street_number integer NOT NULL,
    street_name character varying NOT NULL,
    street_suffix character varying NOT NULL,
    line_2 character varying,
    city character varying(30),
    state character varying(40),
    country character varying(40),
    zip character varying(10)
);


ALTER TABLE public.addresses OWNER TO figgefenk;

--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.carts (
    id integer NOT NULL,
    user_id integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT '2024-02-07 14:54:45.814819-05'::timestamp with time zone,
    created_by character varying,
    updated_by character varying
);


ALTER TABLE public.carts OWNER TO figgefenk;

--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    user_id integer,
    cart_id integer,
    base_price money NOT NULL,
    total_price money NOT NULL,
    payment_card_id integer,
    shipping_address_id integer,
    billing_address_id integer,
    status public.order_status DEFAULT 'checkout'::public.order_status NOT NULL
);


ALTER TABLE public.orders OWNER TO figgefenk;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_cards; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.payment_cards (
    id integer NOT NULL,
    user_id integer,
    number character varying(20) NOT NULL,
    security_code character varying(5) NOT NULL,
    billing_address_id integer,
    billing_first_name character varying NOT NULL,
    billing_last_name character varying NOT NULL,
    card_type character varying(10) NOT NULL
);


ALTER TABLE public.payment_cards OWNER TO figgefenk;

--
-- Name: payment_cards_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.payment_cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.product_images (
    id integer NOT NULL,
    product_id integer,
    url character varying NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    created_by character varying,
    updated_by character varying
);


ALTER TABLE public.product_images OWNER TO figgefenk;

--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.products (
    id integer NOT NULL,
    sku integer NOT NULL,
    name character varying(50) NOT NULL,
    quantity integer NOT NULL,
    base_price money NOT NULL,
    has_discount boolean NOT NULL,
    discount_price money,
    short_description character varying,
    long_description text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    created_by character varying,
    updated_by character varying
);


ALTER TABLE public.products OWNER TO figgefenk;

--
-- Name: products_carts; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.products_carts (
    id integer NOT NULL,
    cart_id integer,
    product_id integer,
    quantity integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    created_by character varying,
    updated_by character varying
);


ALTER TABLE public.products_carts OWNER TO figgefenk;

--
-- Name: products_carts_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.products_carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: figgefenk
--

CREATE TABLE public.users (
    id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    email_address character varying NOT NULL,
    phone character varying NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    created_by character varying,
    updated_by character varying
);


ALTER TABLE public.users OWNER TO figgefenk;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: figgefenk
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: payment_cards payment_cards_number_key; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.payment_cards
    ADD CONSTRAINT payment_cards_number_key UNIQUE (number);


--
-- Name: payment_cards payment_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.payment_cards
    ADD CONSTRAINT payment_cards_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: products_carts products_carts_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.products_carts
    ADD CONSTRAINT products_carts_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: users users_email_address_key; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_address_key UNIQUE (email_address);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: addresses addresses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: carts carts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders orders_billing_address_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_billing_address_id_fkey FOREIGN KEY (billing_address_id) REFERENCES public.addresses(id);


--
-- Name: orders orders_cart_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: orders orders_payment_card_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_payment_card_id_fkey FOREIGN KEY (payment_card_id) REFERENCES public.payment_cards(id);


--
-- Name: orders orders_shipping_address_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_shipping_address_id_fkey FOREIGN KEY (shipping_address_id) REFERENCES public.addresses(id);


--
-- Name: orders orders_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: payment_cards payment_cards_billing_address_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.payment_cards
    ADD CONSTRAINT payment_cards_billing_address_id_fkey FOREIGN KEY (billing_address_id) REFERENCES public.addresses(id);


--
-- Name: payment_cards payment_cards_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.payment_cards
    ADD CONSTRAINT payment_cards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: product_images product_images_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: products_carts products_carts_cart_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.products_carts
    ADD CONSTRAINT products_carts_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: products_carts products_carts_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: figgefenk
--

ALTER TABLE ONLY public.products_carts
    ADD CONSTRAINT products_carts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: TABLE addresses; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.addresses TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.addresses TO r_write_app;


--
-- Name: TABLE carts; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.carts TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.carts TO r_write_app;


--
-- Name: TABLE orders; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.orders TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.orders TO r_write_app;


--
-- Name: TABLE payment_cards; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.payment_cards TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.payment_cards TO r_write_app;


--
-- Name: TABLE product_images; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.product_images TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.product_images TO r_write_app;


--
-- Name: TABLE products; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.products TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.products TO r_write_app;


--
-- Name: TABLE products_carts; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.products_carts TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.products_carts TO r_write_app;


--
-- Name: TABLE users; Type: ACL; Schema: public; Owner: figgefenk
--

GRANT SELECT ON TABLE public.users TO r_read_app;
GRANT INSERT,UPDATE ON TABLE public.users TO r_write_app;


--
-- PostgreSQL database dump complete
--

